# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kova < Formula
  desc "Kova CLI — align portfolios with investment strategies"
  homepage "https://kovatools.com"
  version "0.5.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kovatools/kova-releases/releases/download/v0.5.1/kova_0.5.1_darwin_amd64.tar.gz"
      sha256 "190217be3b4d307b1a12509f27614ebabe0174b46911a2ea5bd781840aa53d74"

      define_method(:install) do
        bin.install "kova"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kovatools/kova-releases/releases/download/v0.5.1/kova_0.5.1_darwin_arm64.tar.gz"
      sha256 "89a63f1435d15e739b78003bdf81ebcbdfc7e216471320d3b09fee750aea8f7b"

      define_method(:install) do
        bin.install "kova"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kovatools/kova-releases/releases/download/v0.5.1/kova_0.5.1_linux_amd64.tar.gz"
      sha256 "9188152c92cbb0b77b685dbf79f215322cdd0a154f420da7d9ff780e1639e703"
      define_method(:install) do
        bin.install "kova"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kovatools/kova-releases/releases/download/v0.5.1/kova_0.5.1_linux_arm64.tar.gz"
      sha256 "bc5ffe5f795d63a1db8cbd4f0b2a6696a73522bb6a85cc295ab0e985417a507f"
      define_method(:install) do
        bin.install "kova"
      end
    end
  end

  test do
    system "#{bin}/kova", "--version"
  end
end
