# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kova < Formula
  desc "Kova CLI — align portfolios with investment strategies"
  homepage "https://kovatools.com"
  version "0.1.2"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kovatools/kova-releases/releases/download/v0.1.2/kova_0.1.2_darwin_amd64.tar.gz"
      sha256 "097def9e956cbea2a5685933d1ed0bf6e00d80437c7e7862a13093bb99128271"

      define_method(:install) do
        bin.install "kova"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kovatools/kova-releases/releases/download/v0.1.2/kova_0.1.2_darwin_arm64.tar.gz"
      sha256 "00ad50c3ec762faa9e27d2fe8c8c95e562ae0e05ec7ab5cdc684e7b01cbc76b2"

      define_method(:install) do
        bin.install "kova"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kovatools/kova-releases/releases/download/v0.1.2/kova_0.1.2_linux_amd64.tar.gz"
      sha256 "eccc5dec8aea560281eb28231c2f3336e196155f5d68f5fe45d5c3c5ebc04b00"
      define_method(:install) do
        bin.install "kova"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kovatools/kova-releases/releases/download/v0.1.2/kova_0.1.2_linux_arm64.tar.gz"
      sha256 "be275bc11af5e81cc219334bd1d55801266dae79e1eb4b4f9d16c92d4bf3b53e"
      define_method(:install) do
        bin.install "kova"
      end
    end
  end

  test do
    system "#{bin}/kova", "--version"
  end
end
