# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kova < Formula
  desc "Kova CLI — align portfolios with investment strategies"
  homepage "https://kovatools.com"
  version "0.4.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kovatools/kova-releases/releases/download/v0.4.0/kova_0.4.0_darwin_amd64.tar.gz"
      sha256 "e5e4cf577d53fbda981052a7d9b297255ee78207162fe14f93c704940da460c1"

      define_method(:install) do
        bin.install "kova"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kovatools/kova-releases/releases/download/v0.4.0/kova_0.4.0_darwin_arm64.tar.gz"
      sha256 "434a382a97f60d5c9604949097564d7baab14ffc841122dc5399d3b45461a72b"

      define_method(:install) do
        bin.install "kova"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kovatools/kova-releases/releases/download/v0.4.0/kova_0.4.0_linux_amd64.tar.gz"
      sha256 "f702b7beeec0316d489b6c1cb8574e811d464b066274935b5021172d64605b64"
      define_method(:install) do
        bin.install "kova"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kovatools/kova-releases/releases/download/v0.4.0/kova_0.4.0_linux_arm64.tar.gz"
      sha256 "275ae348f350d5ffc553db3e6a80bd7cadbf148451d6239ba9486f959d6aa45f"
      define_method(:install) do
        bin.install "kova"
      end
    end
  end

  test do
    system "#{bin}/kova", "--version"
  end
end
